env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {
  react/prop-types: 0,
  import/no-named-as-default: 0,
  import/no-named-as-default-member: 0,
  no-nested-ternary: 0,
  react/jsx-props-no-spreading: 0,
  jsx-a11y/click-events-have-key-events: 0,
  jsx-a11y/no-static-element-interactions: 0,
  react/no-array-index-key: 0,
  jsx-a11y/label-has-associated-control: 0,
  jsx-a11y/anchor-is-valid: 0
}
